### ISSUE TITLE
[Bug]: fatal "InvalidStateError: readyState not OPEN" error after losing connection

### ISSUE THREAD

**Issue by Macil** [discordeno/discordeno#3519] opened 2024-03-31 03:42 UTC
### Runtime

Deno

### Runtime Version

1.42.0

### Version

18.0.1

### Describe the bug

Sometimes when I leave a Discord bot running on my computer, let it fall asleep, and then come back on, I find that the bot has exited with this error output:

```
error: Uncaught (in promise) InvalidStateError: readyState not OPEN
      shard.socket?.send(
                    ^
    at WebSocket.send (ext:deno_websocket/01_websocket.js:326:13)
    at https://deno.land/x/discordeno@18.0.1/gateway/shard/startHeartbeating.ts:52:21
    at eventLoopTick (ext:core/01_core.js:203:13)
```

This doesn't always happen when my bot is running while my computer falls asleep. Sometimes it works fine.

I have not looked into Discordeno's code, but having previously developed programs using Websockets and running into the same "readyState not OPEN" error, I know that this can be caused by calling .send() on a Websocket that is still connecting to a server or when the connection has been closed already. I think it's likely that Discordeno has a heartbeat timer that can call .send() while the connection is closed and not yet reopened and/or while the connection has been previously closed and is still reconnnecting now. The fix would be to either make the heartbeat function check the current state of the Websocket before sending with it, or to make the heartbeat timer shut down entirely once the websocket has been closed and restart once a new websocket connection has been established.

### What should've happened?

Discordeno should always be able to handle a connection closing and reopening without a fatal error.

### Code to reproduce the bug

```typescript
import "https://deno.land/std@0.220.1/dotenv/load.ts";
import {
  createBot,
  Intents,
  startBot,
} from "https://deno.land/x/discordeno@18.0.1/mod.ts";

const bot = createBot({
  token: Deno.env.get("DISCORD_TOKEN")!,
  intents: Intents.Guilds | Intents.GuildMessages | Intents.DirectMessages |
    Intents.MessageContent,
  events: {
    ready(bot, payload) {
      console.log(new Date(), "ready");
    },
    messageCreate(bot, message) {
      console.log(new Date(), "messageCreate");
    },
  },
});
await startBot(bot);
```

**Comment by Macil** [comment] 2024-04-29 03:50
I decided to look into the code behind this so I could fix it myself, but it looks like this issue was already solved in 2714e1e7d1f493891c97ffe248160aaf912da87e, as the refactored startHeartbeating method in Shard.ts now checks the socket's readyState (through a call to `this.isOpen()`) immediately before calling send on it, so it won't try to send a heartbeat for a connection that's closed or still connecting. However, there haven't been any new releases since that commit. Is a release planned?

**Comment by Fleny113** [comment] 2024-04-29 04:39
> I decided to look into the code behind this so I could fix it myself, but it looks like this issue was already solved in [2714e1e](https://github.com/discordeno/discordeno/commit/2714e1e7d1f493891c97ffe248160aaf912da87e), as the refactored startHeartbeating method in Shard.ts now checks the socket's readyState (through a call to `this.isOpen()`) immediately before calling send on it, so it won't try to send a heartbeat for a connection that's closed or still connecting. However, there haven't been any new releases since that commit. Is a release planned?

The node migration is v19 that is still in development, so it's not yet released but there is a per-commit version (stuck to an old commit rn, see #2977). You are using Deno so to use the package you need to use the deno npm compatibility and use the `@discordeno/bot` package.

If you want to update to v19 there are some changes that aren't too much documented at the moment (like desired proprieties) but if you face any issue you can ask on our discord server (https://discord.gg/ddeno)

**Comment by Macil** [comment] 2024-04-29 08:06
Trying to use the latest version (19.0.0-next.6ad4e1d) of the `@discordeno/bot` package fails with an error "Could not find npm package '@discordeno/gateway' matching '19.0.0-alpha.1'." (And trying to use the previous version, 19.0.0-next.d81b28a, fails because my `events.messageCreate` callback gets called with a message object that's just `{ bitfield: ToggleBitfield { bitfield: 0 }, flags: ToggleBitfield { bitfield: 0 } }`).

For the moment I've made [a fork of the repo published on deno.land](https://deno.land/x/discordeno_patched@18.0.2/mod.ts) at 18.0.1 with [my attempt at a fix](https://github.com/Macil/discordeno/commit/b30b647ab980da47fbec507d79b1925a5e2acf29).

**Comment by Fleny113** [comment] 2024-04-29 11:11
> Trying to use the latest version (19.0.0-next.6ad4e1d) of the `@discordeno/bot` package fails with an error "Could not find npm package '@discordeno/gateway' matching '19.0.0-alpha.1'." (And trying to use the previous version, 19.0.0-next.d81b28a, fails because my `events.messageCreate` callback gets called with a message object that's just `{ bitfield: ToggleBitfield { bitfield: 0 }, flags: ToggleBitfield { bitfield: 0 } }`).
> 
> (For the moment I've made [a fork of the repo published on deno.land](https://deno.land/x/discordeno_patched@18.0.2/mod.ts) at 18.0.1 with [my attempt at a fix](https://github.com/Macil/discordeno/commit/b30b647ab980da47fbec507d79b1925a5e2acf29).)

I will look into the npm error, for the version before it's because of desired proprieties, you need to be explit on what proprieties you want on the Message object, the Interaction object and so on from bot.transformers.desiredProprieties

**Comment by Macil** [comment] 2024-04-30 02:04
I've actually just run into a new similar error while waking up my computer while using Discordeno, that seems to be in parts of code that are unchanged in v19:

```
error: Uncaught (in promise) InvalidStateError: readyState not OPEN
  shard.socket?.send(JSON.stringify(message));
                ^
    at WebSocket.send (ext:deno_websocket/01_websocket.js:326:13)
    at send (https://deno.land/x/discordeno_patched@18.0.2/gateway/shard/send.ts:26:17)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async Object.send (https://deno.land/x/discordeno_patched@18.0.2/gateway/shard/createShard.ts:147:14)
```

The relevant parts of send.ts (in v18, but v19 still has this same code as-is refactored into Shard.ts):
https://github.com/discordeno/discordeno/blob/c522cd9a0ee973d3862021bd80e26e2f62a6d983/gateway/shard/send.ts#L3-L27

It seems like when `await checkOffline(...);` finished, the socket wasn't in the open state. Looking at the body of checkOffline(), the function could resolve while the socket is closed if the offlineSendQueue was resolved while the socket was closed.

Here are the places that the offlineSendQueue is resolved (v19 code, also identical here to v18):

https://github.com/discordeno/discordeno/blob/687c29dd7a520378b777aac3c5203f873cff7307/packages/gateway/src/Shard.ts#L429-L450

My guess is that the socket can be closed at this point, possibly because of any `awaits` above this code within the same function or because of other asynchronous steps between the message being read on the socket and this function being called. This seems confirmed to me because of this line above within the same function handling this exact condition, which would prevent this issue if done for RESUMED and READY packet handling too: https://github.com/discordeno/discordeno/blob/687c29dd7a520378b777aac3c5203f873cff7307/packages/gateway/src/Shard.ts#L340-L343

I'm not sure if `if (!this.isOpen()) return` above handling RESUMED and READY packets would be the best solution, or if code in the rest of the function is still important to run even when the socket is closed in which case a tighter `if (this.isOpen()) {` block around some of the code dealing with offlineSendQueue would be better.

Also I noticed that the offlineSendQueue is never emptied. The current code is a memory leak, though a very minor one because I think already-called Promise resolvers don't keep references to anything. And kind of a nitpick but a offlineSendQueue.forEach call would be a little better than a offlineSendQueue.map call if you don't want a new result list to be returned from the call. Here's a suggested fix which clears it. The resolve() calls don't do any real work synchronously and only cause the promise to execute its callbacks later in a microtask, so there's no risk that more items will be added to the offlineSendQueue in between the time we resolve everything in it and when we empty it.

```diff
       case 'RESUMED':
+        if (!this.isOpen()) return
         this.state = ShardState.Connected
         this.events.resumed?.(this)

         // Continue the requests which have been queued since the shard went offline.
-        this.offlineSendQueue.map((resolve) => resolve())
+        this.offlineSendQueue.forEach((resolve) => resolve())
+        this.offlineSendQueue.length = 0

         this.resolves.get('RESUMED')?.(packet)
         this.resolves.delete('RESUMED')
         break
       case 'READY': {
+        if (!this.isOpen()) return
         // Important for future resumes.
         const payload = packet.d as DiscordReady

         this.resumeGatewayUrl = payload.resume_gateway_url

         this.sessionId = payload.session_id
         this.state = ShardState.Connected

         // Continue the requests which have been queued since the shard went offline.
         // Important when this is a re-identify
-        this.offlineSendQueue.map((resolve) => resolve())
+        this.offlineSendQueue.forEach((resolve) => resolve())
+        this.offlineSendQueue.length = 0
```

**Comment by Fleny113** [comment] 2024-04-30 05:19
At this point you made me notice another problem, if the events we call are sync calls to something sync blocking wouldn't that also cause the promise to resolve while the shard could have got closed by discord? Because if yes then there is also that to account for

**Comment by Macil** [comment] 2024-04-30 19:13
When `this.offlineSendQueue.forEach((resolve) => resolve())` is called, everything waiting on checkOffline() including the Shard send() method resumes in a microtask which is scheduled after the current JS execution ends but before any more IO events get dispatched to JS (like a websocket close event), so I think with my suggested fix, the only way the socket can close between checkOffline() ending and the send call in the Shard send() method is if Discordeno itself calls `socket.close()` in that time. (For example, this could happen if there are multiple places in Discordeno that are concurrently waiting on calls to `await checkOffline(...);`, the offlineSendQueue gets resolved, the first waiter on checkOffline() immediately calls `socket.close()`, and then all of the other subsequent waiters find the socket is closed. However, if Discordeno never calls `socket.close()`, or at least never calls it immediately after an `await checkOffline(...);`, then there shouldn't be any risk of that.)

*If* there's a risk of that or we want the code to be solid against that kind of thing, then offlineSendQueue needs not to be a list of promise resolvers that are all resolved together all at once, but a list of callbacks that are sequentially executed with a fresh isOpen() check before each one starts, so if one callback calls socket.close() then the subsequent callbacks stay queued:

```ts
class Shard {
  socket: WebSocket | undefined;
  isOpen() {
    return this.socket?.readyState === WebSocket.OPEN;
  }
  #runWhenOnlineCallbacks: Array<() => void> = [];
  #executeRunWhenOnlineCallbacks() {
    while (this.#runWhenOnlineCallbacks.length) {
      if (!this.isOpen()) break;
      const callback = this.#runWhenOnlineCallbacks.shift()!;
      callback();
    }
  }
  runWhenOnline<T>(callback: () => T, highPriority: boolean): Promise<T> {
    return new Promise((resolve) => {
      const queuedCallback = () => {
        resolve(callback());
      };
      if (highPriority) {
        // Higher priority requests get added at the beginning of the array.
        this.#runWhenOnlineCallbacks.unshift(queuedCallback);
      } else {
        this.#runWhenOnlineCallbacks.push(queuedCallback);
      }
    });
  }
  async send(message: ShardSocketRequest, highPriority: boolean): Promise<void> {
    await this.runWhenOnline(() => {
      this.socket!.send(JSON.stringify(message));
    }, highPriority);
  }
  async discordMessage(message) {
    // ...
    // some awaits etc
    if (message.type === 'RESUME') {
      this.#executeRunWhenOnlineCallbacks();
    }
    // ...
  }
}
```

**Comment by Fleny113** [comment] 2024-07-26 19:30
I wanted to try to fix this issue, however I couldn't get a way to reproduce it.

On a code standpoint every time we call the `WebSocket.send` method it seems to have a sync check on the status of the WebSocket (the `if (!this.isOpen()) return` there are in the code). The only one that does this check asynchronously is the `send` method, so that one due to the microtask scheduling may execute code after the TCP has been dropped. However, the original issue was with the heartbeat system where we do check for the connection status, so a reproduction would be useful

**Comment by dave9123** [comment] 2024-08-31 23:53
This problem happened to me recently
![Screenshot_2024-09-01-06-52-59-59.jpg](https://github.com/user-attachments/assets/da16c6c5-9d2f-4cd7-9643-f5ff7f66c665)

**Comment by Fleny113** [comment] 2024-09-01 06:34
> This problem happened to me recently
What version of Deno are you using? From the screenshot it seems you are using discordeno v17, if this is something you can reproduce, can you try to reproduce it on discordeno v19?

**Comment by dave9123** [comment] 2024-09-01 10:11
I'm using Deno version 1.14.1On Sep 1, 2024 13:35, Fleny ***@***.***> wrote:

This problem happened to me recently

What version of Deno are you using? From the screenshot it seems you are using discordeno v17, if this is something you can reproduce, can you try to reproduce it on discordeno v19?

**Comment by dave9123** [comment] 2024-09-14 08:00
Error shows for me again this morning
![Screenshot_2024-09-14-14-58-57-49_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/55132c1b-1e95-43f8-8727-c49a13833bbf)

**Comment by Fleny113** [comment] 2024-09-14 14:59
> Error shows for me again this morning

With discordeno v17 still? If so, you should try to repro this on v19, if you can provide a repro even on v17 that would be more than nothing even if a repro with v19 is preferred

**Comment by AwesomeStickz** [comment] 2024-11-27 08:40
Couldn't reproduce this issue in v19 anymore so closing this issue but feel free to reopen it if you still do see it

**Closed by AwesomeStickz** 2024-11-27 08:40 UTC
Labels: t-bug, w-verified
